const data = {
  products: [
    {
      name: 'Athletic Shoe',
      slug: 'Athletic- Shoe',
      category: 'Shoes',
      image: 'https://images.journeys.com/images/products/1_687316_ZM.JPG', // 679px × 829px
      price: 39.98,
      InStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Set a new standard this season with the Pacer Future Slip On Athletic Shoe from PUMA! These breathable slip-on sneakers feature mesh uppers with a stretchy design for easy on and off, SoftFoam+ insoles for premium comfort, compression-molded EVA midsoles, and durable rubber outsoles for flexible traction.',
    },
    {
      name: 'Mens adidas Bravada ',
      slug: 'Mens-adidas-Bravada ',
      category: 'Shoes',
      image: 'https://images.journeys.com/images/products/1_729893_MD.JPG', // 679px × 829px
      price: 59.60,
      InStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Drop into the season with the retro styling of the new Bravada 2.0 Athletic Shoe by adidas! This skate-inspired sneaker rocks sturdy canvas uppers with Cloudfoam cushioning for comfort and a vulcanzied sole for flexible traction.',
    },
    {
      name: 'Cotton Fit-and-Flare Dress',
      slug: 'Cotton-Fit-and-Flare-Dress',
      category: 'Clothes',
      image: 'https://www.rlmedia.io/is/image/PoloGSI/s7-1348741_alternate10?$rl_df_pdp_5_7_a10$',
      price: 250,
      InStock: 20,
      brand: 'Lauren Petite',
      rating: 4.0,
      numReviews: 10,
      description: 'Crafted from soft waffle-knit cotton, this dress features a feminine fit-and-flare silhouette.',
    },
    {
      name: 'Pepsi Cola Zero Sugar Soda Pop',
      slug: 'Athletic- Shoe',
      category: 'Groceries',
      image: 'https://i5.walmartimages.com/asr/c0747dca-c904-4561-9f8f-f2da036c9625.049712fc90d3a29d5284e6db7f731436.jpeg', // 679px × 829px
      price: 39.98,
      InStock: 10,
      brand: 'Softdrink',
      rating: 4.5,
      numReviews: 10,
      description: 'Pepsi Zero Sugar (formerly Pepsi Max) quietly downgraded the product formula to remove half the caffeine and take out the ginseng root extract, which are the reasons most people liked it. (The label now says only “Improved Taste!”) It is not. It is a completely different product and the Nutrition Label on this site does not reflect the current / misleading product. I am disappointed a product.',
    },
    {
      name: "Men's Short Sleeve T-Shirt with Pocket",
      slug: 't-sh',
      category: 'T-shirts',
      image: 'https://prd.cc.duluthtrading.com/dw/image/v2/BBNM_PRD/on/demandware.static/-/Sites-dtc-master-catalog/default/dw08437ba7/images/large/22950_OGR.jpg?sw=680&q=40',
      price: 25,
      InStock: 15,
      brand: 'Tee',
      rating: 4.5,
      numReviews: 14,
      description: 'Basic tees are not all created equal. Some are scratchy, see-through, prone to stretching out of shape. The 40 Grit™ Short Sleeve T Shirt gives you a basic price, with a good solid shirt for your money. 100% cotton jersey is soft and comfortable, the way you like. “Honestly, they’re great shirts. Soft and flexible. Very comfortable to wear,” says Dude in the Northeast. A large front pocket is included. Neck tape feels soft against your skin (no scraggly unfinished seams). Neck trim holds its shape. So why settle for anything less?',
    },
    
    {
      name: "Banana",
      slug: 't-sh',
      category: 'Fruits',
      image: 'https://i5.walmartimages.com/asr/4b15d1c6-03e7-489b-96cb-7d4b1edeb927.042464e5bc52fa0421f255d04ec525a4.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF',
      price: 25,
      InStock: 15,
      brand: 'Organic',
      rating: 4.5,
      numReviews: 14,
      description: "Enjoy the sweet, tropical taste of Marketside Organic Bananas. Bananas are a good source of several vitamins and minerals including potassium, vitamin B6 and vitamin C and are low in sodium. Enjoy them at breakfast, lunch, dessert, or anytime you want a healthy snack. Use them to make a loaf of moist banana bread and enjoy with a hot cup of coffee in the mornings or layer them with pudding and vanilla wafer cookies for a light, sweet banana pudding that's perfect for dessert. Simply peel open the banana and savor the delicious taste of this sweet fruit. Bring home Marketside Organic Bananas and make them a part of your day.",
    },

    {
      name: 'School Pantery',
      slug: 'adidas-fit-pant',
      category: 'Groceries',
      image: 'https://i5.walmartimages.com/asr/5df9dabc-a50f-4b3f-83b0-b86b74d6a177.661a96a2cd2949b72f52ace01ea88795.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF',
      price: 65,
      InStock: 5,
      brand: 'Organic',
      rating: 4.5,
      numReviews: 10,
      description: "GO TO YOUR SKIPPY PLACE! With a hearty snack or a robust sandwich, SKIPPY peanut butter hits the spot with the right combination of sweet and savory peanut flavor. SKIPPY Peanut Butter makes nutritious delicious with foods like whole grain bread, fruit and milk – so spread the smiles! Our peanut butter helps restore energy and leaves you feeling charged. It’s been a staple on grocery lists and in pantries for over 80 years! Made with four simple ingredients, we only use real roasted peanuts with no added preservatives – no separation and no oily mess",
    },

    {
      name: 'Women Red Heels Sandal',
      slug: 'Women-Red',
      category: 'Shoes',
      image: '/img/1.png',
      price: 39,
      InStock: 5,
      brand: 'brand',
      rating: 4.5,
      numReviews: 10,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },

    
    {
      name: 'Orange',
      slug: 'adidas-fit-pant',
      category: 'Fruits',
      image: 'https://i5.walmartimages.com/asr/35e5e43b-d7f7-4c05-ad55-d2df5404c1cd_1.8a8b9be88694f526967d6d5b24c78bae.jpeg',
      price: 65,
      InStock: 5,
      brand: 'Organic',
      rating: 4.5,
      numReviews: 10,
      description: "Enjoy the fresh sweetness of Marketside Organic Oranges. A great source of vitamin C, these oranges can be a satisfying afternoon snack, or you can use them in a variety of recipes. For breakfast, use these oranges to make a rich and creamy smoothie or serve them alongside your pancakes, sausage, and eggs. Slice these oranges and use them to add flavor to a lunchtime salad or as a garnish for your favorite adult beverage. Oranges are used in many tasty desserts like ambrosia, orange bars, and zesty orange pie. Get creative in the kitchen and make homemade orange marmalade or a refreshing orange sorbet. However you choose to use them, Marketside Organic Oranges add flavor to any meal or beverage.",
    },
    {
      name: 'Velcro Ballerinas For Girls  (Pink)',
      slug: 'Velcro- Ballerinas',
      category: 'Shoes',
      image: '/img/5.png',
      price: 89,
      InStock: 5,
      brand: 'brand',
      rating: 4.5,
      numReviews: 10,
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
  ],
};
export default data;
